qapi: Catch invalid doc text section
If a documented field doesn't exist in the schema, we throw an unobvious
error:

  GEN     qapi-gen
Traceback (most recent call last):
  File "/stor/work/qemu/scripts/qapi-gen.py", line 57, in <module>
    main(sys.argv)
  File "/stor/work/qemu/scripts/qapi-gen.py", line 53, in main
    gen_doc(schema, args.output_dir, args.prefix)
  File "/stor/work/qemu/scripts/qapi/doc.py", line 270, in gen_doc
    vis.symbol(doc, schema.lookup_entity(doc.symbol))
  File "/stor/work/qemu/scripts/qapi/doc.py", line 253, in symbol
    entity.visit(self)
  File "/stor/work/qemu/scripts/qapi/common.py", line 1161, in visit
    self.member_names(), self.prefix)
  File "/stor/work/qemu/scripts/qapi/doc.py", line 212, in visit_enum_type
    member_func=texi_enum_value)))
  File "/stor/work/qemu/scripts/qapi/doc.py", line 195, in texi_entity
    + texi_sections(doc))
  File "/stor/work/qemu/scripts/qapi/doc.py", line 158, in texi_members
    items += member_func(section.member) + desc
  File "/stor/work/qemu/scripts/qapi/doc.py", line 131, in texi_enum_value
    return '@item @code{%s}\n' % value.name
AttributeError: 'NoneType' object has no attribute 'name'

Let's catch it when the section is invalid and print a more informative
message instead.

Signed-off-by: Fam Zheng <famz@redhat.com>